modLoader="javafml"
loaderVersion="[33,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Jan-Marvin/simple-auto-fishing/issues"

[[mods]]
modId="simpleautofishing"
version="${file.jarVersion}"
displayName="Simple Auto Fishing"
authors="Jan-Marvin"
#updateJSONURL=""
displayURL="https://github.com/Jan-Marvin/simple-auto-fishing"
logoFile="saf.png"
description="Simple Auto Fishing"

[[dependencies.simpleautofishing]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.4]"
	ordering="NONE"
	side="BOTH"
