modLoader="javafml" 
loaderVersion="[65,)"
license="CC BY-NC-ND 4.0"
issueTrackerURL="https://github.com/Jan-Marvin/simple-auto-fishing/issues"

[[mods]]
modId="simpleautofishing"
version="1.8.0"
displayName="Simple Auto Fishing"
authors="Jan-Marvin"
displayURL="https://github.com/Jan-Marvin/simple-auto-fishing"
logoFile="saf.png"
description='''Simple Auto Fishing'''
