modLoader="javafml" 
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Jan-Marvin/simple-auto-fishing/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
displayURL="https://github.com/Jan-Marvin/simple-auto-fishing"
logoFile="saf.png"
description='''${mod_description}'''
