modLoader="javafml"
loaderVersion="[35,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Jan-Marvin/simple-auto-fishing/issues"

[[mods]]
modId="simpleautofishing"
version="${mod_version}"
displayName="Simple Auto Fishing"
authors="Jan-Marvin"
#updateJSONURL=""
displayURL="https://github.com/Jan-Marvin/simple-auto-fishing"
logoFile="saf.png"
description="Simple Auto Fishing"

[[dependencies.simpleautofishing]]
	modId="forge"
	mandatory=true
	versionRange="[35,)"
	ordering="AFTER"
	side="CLIENT"
