modLoader="javafml"
loaderVersion="[${loader_version},)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Jan-Marvin/simple-auto-fishing/issues"

[[mods]]
modId="simpleautofishing"
version= "${mod_version}"
displayName="Simple Auto Fishing"
authors="Jan-Marvin"
displayURL="https://github.com/Jan-Marvin/simple-auto-fishing"
logoFile="saf.png"
description='''Simple Auto Fishing'''

[[dependencies.simpleautofishing]]
	modId="forge"
	mandatory=true
	versionRange="[${forge_version},)"
	ordering="NONE"
	side="BOTH"

[[dependencies.simpleautofishing]]
	modId="minecraft"
	mandatory=true
	versionRange="[${minecraft_version}]"
	ordering="NONE"
	side="BOTH"
